// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TL4_SHOP.Data;

#nullable disable

namespace TL4_SHOP.Migrations
{
    [DbContext(typeof(_4tlShopContext))]
    partial class _4tlShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TL4_SHOP.Data.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangID");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("ChiTietId")
                        .HasName("PK__ChiTietD__B117E9EAF1299D72");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHang", null, t =>
                        {
                            t.HasTrigger("trg_CTDH_InsertUpdate");

                            t.HasTrigger("trg_CapNhatSoLuongTon_ChiTietDonHang");

                            t.HasTrigger("trg_DonHang_UpdateTongTien");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.ChiTietNhapHang", b =>
                {
                    b.Property<int>("ChiTietNhapHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietNhapHangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietNhapHangId"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("PhieuNhapId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuNhapID");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("ChiTietNhapHangId")
                        .HasName("PK__ChiTietN__D9FE8A90D5D8DB80");

                    b.HasIndex("PhieuNhapId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietNhapHang", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatSoLuongTonKhiNhap");

                            t.HasTrigger("trg_TinhTongTien");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.DanhMucSanPham", b =>
                {
                    b.Property<int>("DanhMucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DanhMucID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucId"));

                    b.Property<int?>("DanhMucChaId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DanhMucId")
                        .HasName("PK__DanhMucS__1C53BA7B71EFB0D1");

                    b.HasIndex("DanhMucChaId");

                    b.ToTable("DanhMucSanPham", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.DiaChi", b =>
                {
                    b.Property<int>("DiaChiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiaChiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaChiId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoNha")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DiaChiId")
                        .HasName("PK__DiaChi__94E668E696DC2723");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DiaChi", null, t =>
                        {
                            t.HasTrigger("trg_AutoFill_DiaChi");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.DoanhThuTheoNam", b =>
                {
                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal?>("LoiNhuan")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("TongSoDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoLuong")
                        .HasColumnType("int");

                    b.HasKey("Nam")
                        .HasName("PK__DoanhThu__C7D111C2C4C815AF");

                    b.ToTable("DoanhThuTheoNam", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.DoanhThuTheoNgay", b =>
                {
                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<decimal?>("LoiNhuan")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("TongSoDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoLuong")
                        .HasColumnType("int");

                    b.HasKey("Ngay")
                        .HasName("PK__DoanhThu__6BCCE7B20FFD82FF");

                    b.ToTable("DoanhThuTheoNgay", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatDoanhThuTheoNam");

                            t.HasTrigger("trg_CapNhatDoanhThuTheoThang");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.DoanhThuTheoThang", b =>
                {
                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("LoiNhuan")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("TongSoDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoLuong")
                        .HasColumnType("int");

                    b.HasKey("Nam", "Thang")
                        .HasName("PK__DoanhThu__750C5E96CD37571B");

                    b.ToTable("DoanhThuTheoThang", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.DonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DonHangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonHangId"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("int")
                        .HasColumnName("DiaChiID");

                    b.Property<string>("EmailNguoiDat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("TrangThaiDonHangText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiID");

                    b.HasKey("DonHangId")
                        .HasName("PK__DonHang__D159F4DE93253B15");

                    b.HasIndex("DiaChiId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("TrangThaiId");

                    b.ToTable("DonHang", null, t =>
                        {
                            t.HasTrigger("trg_CapNhatDoanhThuTheoNgay");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KhachHangId")
                        .HasName("PK__KhachHan__880F211BBB2BF01B");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.KhoHang", b =>
                {
                    b.Property<int>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("SanPhamId")
                        .HasName("PK__KhoHang__05180FF4F3BF291A");

                    b.ToTable("KhoHang", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhaCungCap", b =>
                {
                    b.Property<int>("NhaCungCapId")
                        .HasColumnType("int")
                        .HasColumnName("NhaCungCapID");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NhaCungCapId")
                        .HasName("PK__NhaCungC__8B8917272738218A");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NhanVienId")
                        .HasName("PK__NhanVien__E27FD7EA80CBD491");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhapHang", b =>
                {
                    b.Property<int>("PhieuNhapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhieuNhapID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuNhapId"));

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("int")
                        .HasColumnName("NhaCungCapID");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("PhieuNhapId")
                        .HasName("PK__NhapHang__DE3A3882C632D946");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NhapHang", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC07288ACA41");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("TL4_SHOP.Data.SanPham", b =>
                {
                    b.Property<int>("SanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanPhamId"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucID");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("GiaSauGiam")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("LaNoiBat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhaCungCapId")
                        .HasColumnType("int")
                        .HasColumnName("NhaCungCapID");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SanPhamId")
                        .HasName("PK__SanPham__05180FF4AC4878EE");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("NhaCungCapId");

                    b.ToTable("SanPham", null, t =>
                        {
                            t.HasTrigger("trg_InsertKhoHang");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.TaoTaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaiKhoanId")
                        .HasName("PK__TaoTaiKh__9A124B658310C38B");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.HasIndex(new[] { "Phone" }, "UQ__TaoTaiKh__5C7E359EF074C186")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__TaoTaiKh__A9D1053489221C10")
                        .IsUnique();

                    b.ToTable("TaoTaiKhoan", null, t =>
                        {
                            t.HasTrigger("trg_InsertKhachHangFromTaiKhoan");

                            t.HasTrigger("trg_InsertNhanVienFromTaiKhoan");

                            t.HasTrigger("trg_UpdateIDs_AfterInsert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TL4_SHOP.Data.TechNews", b =>
                {
                    b.Property<int>("TechNewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechNewsId"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Summary")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("TechNewsId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsFeatured", "PublishedAt");

                    b.ToTable("TechNews", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.TrangThaiDonHang", b =>
                {
                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiID");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrangThaiId")
                        .HasName("PK__TrangTha__D5BF1E85ABD8D594");

                    b.ToTable("TrangThaiDonHang", (string)null);
                });

            modelBuilder.Entity("TL4_SHOP.Data.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("WishlistId")
                        .HasName("PK__Wishlist__233189EBE961249E");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("TL4_SHOP.Data.WishlistItem", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistItemId"));

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("WishlistItemId")
                        .HasName("PK__Wishlist__171E21A136D407A9");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("TL4_SHOP.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("TL4_SHOP.Data.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__DonHa__656C112C");

                    b.HasOne("TL4_SHOP.Data.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__SanPh__66603565");

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TL4_SHOP.Data.ChiTietNhapHang", b =>
                {
                    b.HasOne("TL4_SHOP.Data.NhapHang", "PhieuNhap")
                        .WithMany("ChiTietNhapHangs")
                        .HasForeignKey("PhieuNhapId")
                        .HasConstraintName("FK__ChiTietNh__Phieu__6754599E");

                    b.HasOne("TL4_SHOP.Data.SanPham", "SanPham")
                        .WithMany("ChiTietNhapHangs")
                        .HasForeignKey("SanPhamId")
                        .HasConstraintName("FK__ChiTietNh__SanPh__68487DD7");

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TL4_SHOP.Data.DanhMucSanPham", b =>
                {
                    b.HasOne("TL4_SHOP.Data.DanhMucSanPham", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("DanhMucChaId")
                        .HasConstraintName("FK_DanhMuc_ChaCon");

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("TL4_SHOP.Data.DiaChi", b =>
                {
                    b.HasOne("TL4_SHOP.Data.KhachHang", "KhachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("KhachHangId")
                        .IsRequired()
                        .HasConstraintName("FK__DiaChi__KhachHan__6A30C649");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TL4_SHOP.Data.DonHang", b =>
                {
                    b.HasOne("TL4_SHOP.Data.DiaChi", "DiaChi")
                        .WithMany("DonHangs")
                        .HasForeignKey("DiaChiId")
                        .HasConstraintName("FK__DonHang__DiaChiI__6B24EA82");

                    b.HasOne("TL4_SHOP.Data.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK__DonHang__KhachHa__6C190EBB");

                    b.HasOne("TL4_SHOP.Data.TrangThaiDonHang", "TrangThai")
                        .WithMany("DonHangs")
                        .HasForeignKey("TrangThaiId")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__TrangTh__6D0D32F4");

                    b.Navigation("DiaChi");

                    b.Navigation("KhachHang");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("TL4_SHOP.Data.KhoHang", b =>
                {
                    b.HasOne("TL4_SHOP.Data.SanPham", "SanPham")
                        .WithOne("KhoHang")
                        .HasForeignKey("TL4_SHOP.Data.KhoHang", "SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__KhoHang__SanPham__6E01572D");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhapHang", b =>
                {
                    b.HasOne("TL4_SHOP.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("NhapHangs")
                        .HasForeignKey("NhaCungCapId")
                        .HasConstraintName("FK__NhapHang__NhaCun__6EF57B66");

                    b.HasOne("TL4_SHOP.Data.NhanVien", "NhanVien")
                        .WithMany("NhapHangs")
                        .HasForeignKey("NhanVienId")
                        .HasConstraintName("FK__NhapHang__NhanVi__6FE99F9F");

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("TL4_SHOP.Data.PasswordResetToken", b =>
                {
                    b.HasOne("TL4_SHOP.Data.TaoTaiKhoan", "TaiKhoan")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("TaiKhoanId")
                        .IsRequired()
                        .HasConstraintName("FK__PasswordR__TaiKh__70DDC3D8");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TL4_SHOP.Data.SanPham", b =>
                {
                    b.HasOne("TL4_SHOP.Data.DanhMucSanPham", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .HasConstraintName("FK__SanPham__DanhMuc__71D1E811");

                    b.HasOne("TL4_SHOP.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("SanPhams")
                        .HasForeignKey("NhaCungCapId")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__NhaCung__72C60C4A");

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("TL4_SHOP.Data.TaoTaiKhoan", b =>
                {
                    b.HasOne("TL4_SHOP.Data.KhachHang", "KhachHang")
                        .WithMany("TaoTaiKhoans")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__TaoTaiKho__Khach__73BA3083");

                    b.HasOne("TL4_SHOP.Data.NhanVien", "NhanVien")
                        .WithMany("TaoTaiKhoans")
                        .HasForeignKey("NhanVienId")
                        .HasConstraintName("FK__TaoTaiKho__NhanV__74AE54BC");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("TL4_SHOP.Data.Wishlist", b =>
                {
                    b.HasOne("TL4_SHOP.Data.KhachHang", null)
                        .WithMany("Wishlists")
                        .HasForeignKey("KhachHangId");

                    b.HasOne("TL4_SHOP.Data.TaoTaiKhoan", "TaoTaiKhoan")
                        .WithMany("Wishlists")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK__Wishlists__TaiKhoan__778AC167");

                    b.Navigation("TaoTaiKhoan");
                });

            modelBuilder.Entity("TL4_SHOP.Data.WishlistItem", b =>
                {
                    b.HasOne("TL4_SHOP.Data.SanPham", "SanPham")
                        .WithMany("WishlistItems")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__WishlistI__SanPh__75A278F5");

                    b.HasOne("TL4_SHOP.Data.TaoTaiKhoan", "TaoTaiKhoan")
                        .WithMany("WishlistItems")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK_WishlistItem_TaoTaiKhoan");

                    b.HasOne("TL4_SHOP.Data.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .IsRequired()
                        .HasConstraintName("FK__WishlistI__Wishl__76969D2E");

                    b.Navigation("SanPham");

                    b.Navigation("TaoTaiKhoan");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("TL4_SHOP.Data.DanhMucSanPham", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("TL4_SHOP.Data.DiaChi", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("TL4_SHOP.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("TL4_SHOP.Data.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("DonHangs");

                    b.Navigation("TaoTaiKhoans");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhaCungCap", b =>
                {
                    b.Navigation("NhapHangs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhanVien", b =>
                {
                    b.Navigation("NhapHangs");

                    b.Navigation("TaoTaiKhoans");
                });

            modelBuilder.Entity("TL4_SHOP.Data.NhapHang", b =>
                {
                    b.Navigation("ChiTietNhapHangs");
                });

            modelBuilder.Entity("TL4_SHOP.Data.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietNhapHangs");

                    b.Navigation("KhoHang");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("TL4_SHOP.Data.TaoTaiKhoan", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("WishlistItems");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("TL4_SHOP.Data.TrangThaiDonHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("TL4_SHOP.Data.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
